### ISSUE TITLE
default storage class

### ISSUE THREAD

**Issue by aym-frikha** [Barteus/kubeflow-examples#1]
For charmed k8s on openstack you need to specify the default storage class otherwise the jupyter notebook cannot instantiate new volume:

kubectl patch storageclass cdk-cinder -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

**Comment by Barteus** [comment]
Thanks a lot! Commit with documentation addition is already in the main.
https://github.com/Barteus/kubeflow-examples/commit/1ab7a439a087454c4ef54c73604998942f50ea60
